[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#ADEFD1FF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#00203FFF"

# Color used for almost all text.
textColor = "#fff" 