[server]
headless = true
port = 8502
enableCORS = false
enableXsrfProtection = false
mainModule = "Home.py"

[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#C7D3D4FF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#603F83FF"

# Color used for almost all text.
textColor = "#000000"